### ISSUE TITLE
Lab 02-2 - Ex02 - Task 01 Unable to find Headshot field

### ISSUE THREAD

**Issue by KashifKhaan** [MicrosoftLearning/MB-280T03-Design-and-deliver-powerful-customer-experiences-with-Dynamics-365-Customer-Insights#2]
# Module: 02
#### Step: 04

**Description of issue:**
Unable to find the **Headshot** field.

**Screenshots:**
![image](https://github.com/user-attachments/assets/89ebb40b-968e-4ce3-88c8-db610962df97)
![image](https://github.com/user-attachments/assets/dcafc54e-52eb-4a2b-aa69-4e344ae1f199)

**Comment by a-ainamdar** [comment]
Thank you for raising this issue. We will update on this soon. Thank you for your patience!
